name: TestDeployment2

control-plane: {}

default-service: dummy_workflow

services:
  test-workflow:
    name: Test Workflow
    port: 8002
    host: localhost
    source:
      type: local
      name: src
    path: src:my_workflow
