name: HumanInTheLoop

control-plane:
  port: 8000

default-service: hitl_workflow

services:
  hitl_workflow:
    name: HITL Workflow
    source:
      type: local
      name: src
    path: src/workflow_hitl:workflow
