name: Streaming

control-plane:
  port: 8000

default-service: streaming_workflow

services:
  streaming_workflow:
    name: Streaming Workflow
    source:
      type: local
      name: ./e2e_tests/apiserver/deployments/src
    path: ./e2e_tests/apiserver/deployments/src/workflow:streaming_workflow
