name: EnvironmentVariables

control-plane:
  port: 8000

default-service: test_env_workflow

services:
  test_env_workflow:
    name: Workflow
    source:
      type: local
      name: ./e2e_tests/apiserver/deployments/src
    env:
      VAR_1: x  # this gets overwritten because VAR_1 also exists in the provided .env
      VAR_2: y
    env-files:
      - .env  # relative to source path
    path: workflow_env:workflow

  git_workflow:
    name: Git Workflow
    source:
      type: git
      name: https://github.com/run-llama/llama_deploy.git@nerdai/add-environment-variables-to-deployment-defn
    env:
      VAR_1: x  # this gets overwritten because VAR_1 also exists in the provided .env
      VAR_2: y
    env-files:
      - tests/apiserver/data/.env  # relative to source path
    path: tests/apiserver/data/workflow:env_reader_workflow
