register-cp:
	python multi-agent-app/multi_agent_app/core_services/control_plane.py

register-services:
	python multi-agent-app/multi_agent_app/agent_services/secret_agent.py
	python multi-agent-app/multi_agent_app/agent_services/funny_agent.py
	python multi-agent-app/multi_agent_app/additional_services/human_consumer.py
