register:
	python multi-agent-app/multi_agent_app/control_plane.py
	python multi-agent-app/multi_agent_app/agents/secret_agent.py
	python multi-agent-app/multi_agent_app/agents/funny_agent.py
	python multi-agent-app/multi_agent_app/additional_services/human_consumer.py
