name: dependencies

control-plane:
  port: 8000

default-service: echo_workflow

services:
  echo_workflow:
    name: Pretty Echo Workflow
    source:
      type: local
      name: src
    path: workflow:echo_workflow
    python-dependencies:
      - cowpy
      - "."
      - "requirements.txt"
