name: Docker image release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

env:
  DOCKER_REPO_NAME: llamaindex/llama-deploy

jobs:
  build-and-push:
    name: Build base image
    runs-on: ubuntu-latest
    # don't run from forks
    if: github.repository_owner == 'run-llama'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: $DOCKER_REPO_NAME

      - name: Build images
        uses: docker/bake-action@v5
        env:
          IMAGE_TAG_SUFFIX: ${{ steps.meta.outputs.version }}
          LLAMA_DEPLOY_VERSION: ${{ steps.meta.outputs.version }}
        with:
          workdir: docker
          targets: all
          push: true
